const tile=(p,v,icon,label,value,foot,o={})=>{const q=v==="quiet";const W=o.w||250,H=o.h||128;const t=fr(p,{name:"SummaryTile "+label,layout:"vertical",gap:4,width:"fill_container",height:H,cornerRadius:20,padding:o.pad||20,clip:true,effect:q?SH:POP,fill:q?"$card":{type:"gradient",gradientType:"linear",rotation:135,colors:[{color:"$grad-"+v+"-from",position:0},{color:"$grad-"+v+"-to",position:1}]}});const fg=q?"$muted-foreground":"#ffffff";Insert(t,{type:"icon",library:"lucide",icon,name:"deco",layoutPosition:"absolute",x:W-(o.decoS||112)+18,y:H-(o.decoS||112)+30,width:o.decoS||112,height:o.decoS||112,rotation:12,fill:q?"$status-idle":"#ffffff",opacity:q?0.15:0.12});tx(t,label,{fontSize:14,fontWeight:"700",fill:fg});tx(t,value,{fontSize:o.vs||30,fontWeight:"800",fill:q?"$muted-foreground":"#ffffff",name:"value"});fr(t,{name:"grow",height:"fill_container",width:1});foot.forEach(f=>{const [s,c]=Array.isArray(f)?f:[f,fg];wrap(t,s,{fontSize:o.fs||14,fontWeight:"600",fill:c,name:"foot"})});return t};
const taskRow=(p,o={})=>{const r=col(p,{name:"TaskRow",width:"fill_container",fill:o.alert?"$status-danger-soft":"$muted",cornerRadius:14,padding:12,gap:10});const a=row(r,{name:"line1",width:"fill_container",gap:8});tx(a,o.name,{fontSize:14,fontWeight:"700"});pill(a,"進行中","ok",{sm:true});tag(a,"ESCALATE 1","warn");sp(a);if(!o.mobile)tx(a,"波 3 進行中 · 已 18 分",{fontSize:12,fill:"$muted-foreground"});const b=row(r,{name:"progress",width:"fill_container",gap:10});const tr=fr(b,{name:"track",width:"fill_container",height:6,cornerRadius:999,fill:"$card",layout:"none"});Insert(tr,{type:"rectangle",name:"fill",x:0,y:0,width:o.mobile?150:465,height:6,cornerRadius:999,fill:"$primary"});tx(b,"2/4 波",{fontSize:12,fontWeight:"700"});const m=row(r,{name:"members",gap:6,width:"fill_container"});[["designer","ok"],["react-theme","ok"],["react-games",o.alert?"danger":"ok"],["react-pages","idle"],["qa","idle"]].slice(0,o.mobile?3:5).forEach(([n,t])=>pill(m,n,t));if(o.mobile)tag(m,"+2");return r};
const thumb=(p,name,tone,label,lines,o={})=>{const t=col(p,{name:"PaneThumb "+name,width:"fill_container",gap:0,cornerRadius:11,clip:true,fill:"$terminal-bg"});const h=row(t,{name:"chrome",width:"fill_container",height:24,fill:"$terminal-chrome",padding:[0,8],gap:6,theme:{mode:"dark"}});pill(h,label,tone,{sm:true,fill:"#ffffff0d"});tx(h,name,{fontSize:11,fontWeight:"600",fill:"$terminal-fg"});sp(h);tx(h,o.meta||"opus 5.5 · ctx 31%",{fontSize:11,fill:"$terminal-dim"});term(t,lines,{h:o.h||152,fs:11});return t};
const idleRow=(p,name,ver,closed,dots,last,o={})=>{const r=row(p,{name:"IdleProjectRow "+name,width:"fill_container",height:44,cornerRadius:14,padding:[0,12],gap:10,fill:o.hover?"$muted":undefined});ic(r,"chevron-right",16,"$muted-foreground");tx(r,name,{fontSize:14,fontWeight:"700"});tag(r,ver,"neutral",{mono:true});if(!o.mobile)tx(r,"已結案 "+closed,{fontSize:12,fill:"$muted-foreground"});const d=row(r,{name:"sessions",gap:4});dots.forEach(x=>dot(d,x,8));sp(r);tx(r,last,{fontSize:12,fontFamily:M,fill:"$muted-foreground"});return r};
const actGroup=(p,task,proj,time,items,o={})=>{const g=col(p,{name:"ActivityGroup "+task,width:"fill_container",gap:2});const h=row(g,{name:"GroupHead",width:"fill_container",height:28,padding:[0,8],gap:6,cornerRadius:14});ic(h,"list-checks",14,"$brand-violet");tx(h,task,{fontSize:12,fontWeight:"800"});tx(h,"· "+proj,{fontSize:12,fill:"$muted-foreground"});sp(h);tx(h,time,{fontSize:12,fill:"$muted-foreground"});const b=col(g,{name:"GroupBody",width:"fill_container",gap:2,padding:[0,0,0,12],stroke:"$border",strokeWidth:{left:2}});items.forEach(it=>{const r=row(b,{name:"ActivityItem",width:"fill_container",alignItems:"start",gap:10,padding:[6,8],cornerRadius:14});if(it.av)avatar(r,it.av[0],it.av[1],24);else{const w=row(r,{name:"lead",width:24,height:20,justifyContent:"center"});dot(w,"idle",6)}const c=col(r,{name:"body",gap:2,width:"fill_container"});const l=row(c,{name:"l1",gap:6,width:"fill_container"});if(it.actor)tx(l,it.actor,{fontSize:13,fontWeight:"700"});tag(l,it.type,it.tone);if(it.time){sp(l);tx(l,it.time,{fontSize:11,fill:"$muted-foreground"})}wrap(c,it.text,{fontSize:13,fill:"$muted-foreground",lineHeight:1.4})});if(o.more){const m=row(g,{name:"more",padding:[2,0,0,22]});tx(m,o.more,{fontSize:12,fontWeight:"700",fill:"$primary"})}return g};
const T1=[["✻ Seasoning… (2m 11s · ↓ 6.2k tokens)","#e8a87c"],"",["Do you want to overwrite package.json scripts?","$terminal-fg"],["❯ 1. Yes","#7ee0b5"],"  2. Yes, and don't ask again","  3. No, tell Claude what to do",""," esc to cancel",["ctx:31% | Opus 5.5 | 5h:37%","$terminal-dim"]];
const T2=[["● 已完成首頁稿：design/home.webp","$terminal-fg"],["  ⎿ spec.md 寫入 42 行","$terminal-dim"],"",["● Writing design/pages.pen …","$terminal-fg"],["  ⎿ execute ok · 18 nodes","$terminal-dim"],"",["✻ Brewing… (54s · ↓ 2.1k tokens)","#e8a87c"],"",["ctx:44% | Opus 5.5 | 5h:37%","$terminal-dim"]];
const ACT=(blocked)=>[
 ["toybox","collect","2 分鐘前",[blocked?{actor:"react-games",av:["🦊","#ffe2c2"],type:"BLOCKED",tone:"danger",text:"卡在審批：要不要覆寫 package.json 的 scripts？",time:"2 分"}:{actor:"react-games",av:["🦊","#ffe2c2"],type:"DONE",tone:"ok",text:"遊戲頁三個玩具卡元件完成，測試 18 綠",time:"2 分"},{actor:"designer",av:["🐼","#c4ecf2"],type:"DONE",tone:"ok",text:"首頁稿與 spec 完成，見 design/home.webp",time:"6 分"},{type:"spawn",tone:"info",text:"spawn toybox-react-pages（claude L）"}]],
 ["cuteui","dkbo-team-dashboard","27 分鐘前",[{type:"task-close",tone:"ok",text:"task-close merged 6545a3c"},{type:"gate3",tone:"ok",text:"gate3 approved（人：合併）"}]],
 ["toybox","collect","31 分鐘前",[{actor:"reviewer-a",av:["🐸","#dff5c4"],type:"DONE",tone:"ok",text:"review 波 2：Important 0 條，見 report",time:"31 分"},{type:"wave-close",tone:"ok",text:"wave-close 2 · tests ok（pnpm -r test）"},{type:"ESCALATE",tone:"warn",text:"react-theme：token 名要跟 index.css 對齊還是另開 namespace？"}],"再看 3 則"],
 ["panova","sport-frontend-panova","1 小時前",[{type:"ruling",tone:"info",text:"ruling 串接新 API 延後到下一波，先修 headermerge"}]]];
const T3=[["● 三個玩具卡元件完成","$terminal-fg"],["  ⎿ src/games/*.tsx +412 −38","$terminal-dim"],"",["● Bash(pnpm -C apps/web test)","$terminal-fg"],["  ⎿ 18 passed","#7ee0b5"],"",["✻ Cogitating… (1m 2s)","#e8a87c"],"",["ctx:31% | Opus 5.5 | 5h:37%","$terminal-dim"]];
