const pg=page("page-overview-390",3080,0,390,{});
const tb=col(pg,{name:"TopBar mobile",width:"fill_container",fill:"$topbar",effect:SH,gap:0});
const r1=row(tb,{name:"row1",width:"fill_container",height:48,padding:[0,12,0,16],gap:6});ic(r1,"cloud",22,"$brand-blue");tx(r1,"dkbo 儀表板",{fontSize:15,fontWeight:"800"});sp(r1);pill(r1,"1 卡住","danger",{sm:true});pill(r1,"2 熔斷","warn",{sm:true});iconBtn(r1,"sun");
const r2=row(tb,{name:"nav scroll",width:"fill_container",height:44,padding:[0,12],gap:4});NAV.forEach((n,i)=>{const on=i===0;const b=row(r2,{name:"nav "+n,height:32,cornerRadius:999,padding:[0,14],fill:on?"$primary":undefined});tx(b,n,{fontSize:14,fontWeight:on?"700":"600",fill:on?"$primary-foreground":"$muted-foreground"})});
const body=pageBody(pg,{pad:[16,16,24,16]});
const a=pageHeader(body,"layout-dashboard","總覽","4 個專案 · 1 個進行中");iconBtn(a,"monitor-play",{fill:"$muted",color:"$foreground"});
const g1=row(body,{name:"tiles r1",width:"fill_container",gap:12});const g2=row(body,{name:"tiles r2",width:"fill_container",gap:12});
const mo={w:173,h:112,pad:16,vs:24,decoS:72,fs:12};
tile(g1,"ok","rocket","進行中任務","1",["toybox · 波 3/4"],mo);tile(g1,"brand","coins","今日花費","$124.03",["昨日 $198.63"],mo);
tile(g2,"danger","siren","卡住的 agent","1",["react-games"],mo);tile(g2,"warn","gauge","熔斷與額度","2 熔斷",["最短 5 天 20 小時"],mo);
const sec=row(body,{name:"SectionTitle",gap:8});tx(sec,"活躍專案",{fontSize:18,fontWeight:"800"});tag(sec,"1");
const pc=card(body,{name:"ProjectCard collect",padding:16,gap:12,stroke:"$status-danger",strokeWidth:2});cardHead(pc,"collect",null,{after:t=>tag(t,"v0.19.0","neutral",{mono:true})});
taskRow(pc,{name:"全站改版（Toybox）",alert:true,mobile:true});thumb(pc,"toybox-react-games","danger","卡住",T1,{meta:"ctx 31%",h:140});
const os=row(pc,{name:"footer",width:"fill_container",gap:8});pill(os,"claude","idle",{sm:true});sp(os);tx(os,"已結案 7 件 ›",{fontSize:13,fontWeight:"600",fill:"$muted-foreground"});
const rail=card(body,{name:"ActivityRail mobile",padding:12,gap:10});const rh=row(rail,{name:"RailHead",width:"fill_container",padding:[4,6,0,6],gap:6});ic(rh,"sparkles",16,"$brand-violet");tx(rh,"活動動態",{fontSize:16,fontWeight:"700"});tx(rh,"最新 5 則",{fontSize:12,fill:"$muted-foreground"});sp(rh);seg(rh,["全部","需處理"],0,{sm:true});
const A=ACT(1);actGroup(rail,A[0][0],A[0][1],A[0][2],A[0][3]);actGroup(rail,A[1][0],A[1][1],A[1][2],A[1][3]);
const mb=row(rail,{name:"Button 看全部",width:"fill_container",height:36,cornerRadius:999,stroke:"$input",strokeWidth:1,justifyContent:"center",gap:6});tx(mb,"看全部活動（48）",{fontSize:14,fontWeight:"700"});ic(mb,"chevron-down",14,"$muted-foreground");
const ic2=card(body,{name:"IdleProjects mobile",gap:2,padding:[14,8]});const ih=row(ic2,{name:"head",width:"fill_container",padding:[0,8,6,8],gap:8});tx(ih,"閒置專案",{fontSize:16,fontWeight:"700"});tag(ih,"3");sp(ih);ic(ih,"chevron-up",16,"$muted-foreground");
idleRow(ic2,"dkbo-team-dash…","v0.19",5,["ok","idle"],"10-03",{mobile:true});idleRow(ic2,"teamflow","v0.19",10,["idle"],"09-25",{mobile:true});idleRow(ic2,"sport-frontend…","v0.19",17,["idle"],"09-23",{mobile:true});
M390=pg;
