const pg=page("page-task",0,1200,1440,{});topbar(pg,-1,{blocked:1});const body=pageBody(pg);
const bc=row(body,{name:"Breadcrumb",gap:6});ic(bc,"arrow-left",14,"$muted-foreground");tx(bc,"總覽",{fontSize:14,fill:"$muted-foreground"});ic(bc,"chevron-right",14,"$muted-foreground");tx(bc,"collect",{fontSize:14,fill:"$muted-foreground"});ic(bc,"chevron-right",14,"$muted-foreground");tx(bc,"2026-10-04-toybox",{fontSize:14,fontFamily:M,fontWeight:"600"});
const a=pageHeader(body,"list-checks","全站改版（DKBO Toybox 玩具機風）","collect · 2026-10-04-toybox · dk/toybox",{meta:t=>pill(t,"進行中","ok")});btn(a,"看 herdr","outline",{icon:"monitor-play",size:"sm"});btn(a,"複製 focus 指令","ghost",{icon:"copy",size:"sm"});
banner(body,"warn","更新失敗，顯示的是舊資料","dk-status 逾時（collect，12:55）；10 秒後自動重試",{action:"重試"});
const g=row(body,{name:"TaskGrid",width:"fill_container",gap:24,alignItems:"start"});const main=col(g,{name:"Main",width:"fill_container",gap:24});const aside=col(g,{name:"Aside",width:360,gap:16});
const wt=card(main,{name:"WaveTimeline"});cardHead(wt,"波次時間軸",null,{icon:"git-branch"});
const closedWave=(n,who,dur,sha)=>{const r=row(wt,{name:"Wave "+n,width:"fill_container",height:44,fill:"$muted",cornerRadius:14,padding:[0,16],gap:10});tx(r,"波 "+n,{fontWeight:"800"});pill(r,"已關閉","idle",{sm:true,check:true});tx(r,who+" · "+dur,{fontSize:13,fill:"$muted-foreground"});sp(r);tag(r,"tests ok","ok",{icon:"check"});tag(r,sha,"neutral",{mono:true})};
closedWave(1,"backend、frontend","42 分","e710228");closedWave(2,"react-theme、designer","1 小時 6 分","8b83e87");
const w3=col(wt,{name:"Wave 3 current",width:"fill_container",fill:"$muted",cornerRadius:14,padding:16,gap:14});const wh=row(w3,{name:"head",gap:10,width:"fill_container"});tx(wh,"波 3",{fontWeight:"800"});pill(wh,"進行中","ok",{sm:true});tx(wh,"react-games、react-pages、qa",{fontSize:13,fill:"$muted-foreground"});sp(wh);tx(wh,"已 18 分",{fontSize:13,fontWeight:"600"});
const steps=row(w3,{name:"Steps",width:"fill_container",gap:0,alignItems:"start"});[["開波","10-04 12:38","done"],["dev 完成","進行中","cur"],["送審","—","todo"],["裁定","—","todo"],["關閉","—","todo"]].forEach(([l,t,s],i)=>{const c=col(steps,{name:"step "+l,width:"fill_container",gap:6});const tr=row(c,{name:"track",width:"fill_container",gap:0});const d=s==="done"?"$status-ok":s==="cur"?"$primary":"$card";Insert(tr,{type:"ellipse",name:"node",width:14,height:14,fill:d,stroke:s==="todo"?"$input":(s==="cur"?"$card":undefined),strokeWidth:s==="todo"?2:(s==="cur"?3:undefined)});if(i<4)fr(tr,{name:"line",width:"fill_container",height:3,fill:s==="done"?"$status-ok":"$input",cornerRadius:999});tx(c,l,{fontSize:13,fontWeight:"700",fill:s==="todo"?"$muted-foreground":"$foreground"});tx(c,t,{fontSize:12,fontFamily:M,fill:s==="cur"?"$primary":"$muted-foreground"})});
const w4=row(wt,{name:"Wave 4",width:"fill_container",height:44,fill:"$muted",cornerRadius:14,padding:[0,16],gap:10,opacity:0.8});tx(w4,"波 4",{fontWeight:"800",fill:"$muted-foreground"});pill(w4,"未開始","idle",{sm:true});tx(w4,"qa 收尾、整枝評議",{fontSize:13,fill:"$muted-foreground"});
const mt=card(main,{name:"MemberTable",padding:[20,12,8,12]});const mh=row(mt,{name:"hd",width:"fill_container",padding:[0,8]});cardHead(mh,"成員",null,{icon:"users",after:t=>tag(t,"6")});
const PH=(s,t,l)=>c=>{pill(c,l,t,{sm:true})};
tbl(mt,[{l:"成員",w:150},{l:"state",w:96},{l:"目前"},{l:"herdr",w:120},{l:"設定",w:170},{l:"cost",w:72,r:1},{l:"ctx",w:56,r:1}],[
 {c:[c=>{tx(c,"designer",{fontWeight:"700"});tx(c,"波 2",{fontSize:12,fill:"$muted-foreground"})},PH(0,"ok","done"),"首頁稿與 spec 完成，見 design/home.webp",c=>{pill(c,"工作中","ok",{sm:true});ic(c,"monitor-play",14,"$muted-foreground")},c=>tag(c,"claude L · opus/high","brand",{mono:true}),"$12.20","44%"]},
 {c:[c=>{tx(c,"react-games",{fontWeight:"700"});tx(c,"波 3",{fontSize:12,fill:"$muted-foreground"})},PH(0,"danger","blocked"),c=>wrap(c,"等審批：要不要覆寫 package.json 的 scripts？",{fontSize:14,fill:"$status-danger-fg",fontWeight:"600"}),c=>{pill(c,"卡住","danger",{sm:true});ic(c,"monitor-play",14,"$muted-foreground")},c=>tag(c,"claude M · opus/medium","brand",{mono:true}),"$7.53","31%"],sel:true},
 {c:[c=>{tx(c,"react-pages",{fontWeight:"700"});tx(c,"波 3",{fontSize:12,fill:"$muted-foreground"})},PH(0,"ok","working"),"首頁與遊戲頁路由",c=>{pill(c,"工作中","ok",{sm:true});ic(c,"monitor-play",14,"$muted-foreground")},c=>tag(c,"claude M · opus/medium","brand",{mono:true}),"$4.09","22%"]},
 {c:[c=>{tx(c,"react-theme",{fontWeight:"700"});tx(c,"波 2",{fontSize:12,fill:"$muted-foreground"})},PH(0,"idle","done"),"token 與 index.css 對齊",c=>pill(c,"閒置","idle",{sm:true}),c=>tag(c,"claude M · opus/medium","brand",{mono:true}),"$8.02","—"]},
 {c:[c=>{tx(c,"qa",{fontWeight:"700"});tx(c,"波 3",{fontSize:12,fill:"$muted-foreground"})},PH(0,"idle","waiting"),"等 dev 完成",c=>pill(c,"閒置","idle",{sm:true}),c=>tag(c,"claude M · opus/medium","brand",{mono:true}),"—","—"]},
 {c:[c=>{tx(c,"reviewer-a",{fontWeight:"700"});tx(c,"波 2",{fontSize:12,fill:"$muted-foreground"})},PH(0,"idle","done"),"review 波 2：Important 0",c=>pill(c,"無 pane","idle",{sm:true}),c=>tag(c,"claude L · opus/high","brand",{mono:true}),"$10.23","—"]}
]);
const tabs=row(main,{name:"TabsRow",width:"fill_container"});seg(tabs,["驗收標準|10","檔案所有權","裁定|9","訊息|26","事件原文|52"],0);
const ac=card(main,{name:"AcceptanceCard",gap:12});[["AC1 主題 token 與 Toybox 玩具機配色對齊 index.css",1],["AC2 首頁三張玩具卡與遊戲頁路由",1],["AC3 遊戲頁三個玩具卡元件＋單元測試",0],["AC4 e2e：首頁、遊戲頁 1440／390 截圖",0]].forEach(([t,d])=>{const r=row(ac,{name:"ac",width:"fill_container",gap:10,alignItems:"start"});ic(r,d?"square-check":"square",18,d?"$status-ok":"$muted-foreground");wrap(r,t,{fontSize:14})});
const info=card(aside,{name:"TaskInfo",gap:8});cardHead(info,"任務資訊",null,{icon:"info"});dl(info,[["資料夾","2026-10-04-toybox"],["分支","dk/toybox"],["建立","10-04 09:12"],["關卡① 放行","10-04 09:31"],["波進度",r=>tx(r,"2/4 波",{fontSize:13,fontWeight:"700"})],["最後更新","10-04 12:56"]]);
const cost=card(aside,{name:"TaskCost",gap:12});cardHead(cost,"任務花費",null,{icon:"coins"});const big=row(cost,{name:"total",gap:8,alignItems:"end"});tx(big,"$64.98",{fontSize:24,fontWeight:"800"});tx(big,"6 位成員",{fontSize:13,fill:"$muted-foreground"});
dl(cost,[["designer",r=>{tag(r,"L","brand");tx(r,"$12.20",{fontSize:13,fontWeight:"700"})}],["reviewer-a",r=>{tag(r,"L","brand");tx(r,"$10.23",{fontSize:13,fontWeight:"700"})}],["react-theme",r=>{tag(r,"M","brand");tx(r,"$8.02",{fontSize:13,fontWeight:"700"})}],["react-games",r=>{tag(r,"M","brand");tx(r,"$7.53",{fontSize:13,fontWeight:"700"})}],["其他",r=>tx(r,"$27.00",{fontSize:13,fontWeight:"700"})]]);
wrap(cost,"dashboard 未開啟期間的花費可能遺漏",{fontSize:12,fill:"$muted-foreground"});
TASK=pg;
